name: Bug report
description: Report a problem with the ConnectWise CPQ (Sell) n8n community node
labels: [bug]
assignees:
  - msoukhomlinov
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a problem. Please use the latest versions and provide clear reproduction steps.
  - type: textarea
    id: bug-description
    attributes:
      label: What happened?
      description: Briefly describe the issue.
      placeholder: A short description of the problem.
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue.
      placeholder: |
        1. Create a workflow with ...
        2. Configure node with ...
        3. Run the workflow
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect to happen?
      description: Describe the expected behaviour.
      placeholder: Expected result.
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: n8n v1 requires Node 20+. Confirm the version in your runtime.
      placeholder: e.g., 20.15.0
    validations:
      required: true
  - type: input
    id: n8n-version
    attributes:
      label: n8n version
      placeholder: e.g., 1.75.1
    validations:
      required: true
  - type: input
    id: package-version
    attributes:
      label: n8n-nodes-connectwise-cpq version
      placeholder: e.g., 0.1.0
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      multiple: true
      options:
        - Linux
        - Windows
        - MacOS
        - Other (enter below with the version)
  - type: input
    id: os-version
    attributes:
      label: Operating system version (or full name if Other)
    validations:
      required: true
  - type: input
    id: cpq-endpoints
    attributes:
      label: Affected CPQ endpoint(s) (optional)
      placeholder: e.g., GET /api/quotes, PATCH /api/quoteItems/{id}
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Paste relevant logs; they will be formatted automatically.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context (optional)
      description: Any extra details, screenshots, or links.
