name: Feature request
description: Suggest an improvement or new capability for the ConnectWise CPQ (Sell) n8n community node
labels: [enhancement]
assignees:
  - msoukhomlinov
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your suggestion. Please keep it focused and actionable.
  - type: textarea
    id: feature-description
    attributes:
      label: What would you like to add or change?
      description: Briefly describe the feature or improvement.
      placeholder: A short description of the desired capability.
    validations:
      required: true
  - type: textarea
    id: alternative-solution
    attributes:
      label: Current workaround (if any)
      description: How are you handling this today?
      placeholder: Describe any temporary workaround.
  - type: textarea
    id: use-cases
    attributes:
      label: Use cases / examples
      description: Concrete examples or workflows that would benefit.
      placeholder: e.g., Sync quote items to ..., filter quotes by ...
  - type: input
    id: related-endpoints
    attributes:
      label: Related CPQ endpoint(s) (optional)
      placeholder: e.g., /api/quoteTerms, /api/templates
  - type: input
    id: priority
    attributes:
      label: Priority (optional)
      placeholder: Low / Medium / High
