import type {
  IDataObject,
  IExecuteFunctions,
  INodeExecutionData,
  INodeProperties,
} from 'n8n-workflow';
import { NodeOperationError } from 'n8n-workflow';
import { cpqApiRequest, cpqApiRequestAllItems, prepareJsonPatch, buildFiltersFromUi, castUpdateValue } from '../GenericFunctions';
import { MAX_PAGE_SIZE } from './constants';

const QUOTE_ITEM_FIELD_TYPES: Record<string, string> = {
  approvalContentHash: 'string',
  approvalMarginMinimum: 'number',
  approvalOnChange: 'boolean',
  approvalPriceMinimum: 'number',
  basePrice: 'number',
  configId: 'string',
  configPosition: 'integer',
  cost: 'number',
  costModifier: 'string',
  crmReference: 'string',
  cwAgreement: 'string',
  cwClass: 'string',
  defermentPeriods: 'integer',
  dimension1: 'string',
  dimension2: 'string',
  dimension3: 'string',
  dimension4: 'string',
  dimension5: 'string',
  disableRemaps: 'boolean',
  discount: 'number',
  discountAmount: 'number',
  discountAmountConverted: 'number',
  enforceItemModTags: 'boolean',
  etilizeProductId: 'number',
  etilizeSerializedAttributes: 'string',
  extendedCost: 'number',
  extendedPrice: 'number',
  extendedPriceConverted: 'number',
  extendedSuggestedPrice: 'number',
  externalQuoteNumber: 'string',
  externalReference: 'string',
  factorItemMfp: 'string',
  factorQtyFixed: 'number',
  factorQtyMultiplier: 'number',
  federalGovPrice: 'number',
  grossMargin: 'number',
  groupingCode: 'string',
  gsaPrice: 'number',
  gst: 'number',
  gstConverted: 'number',
  gstRate: 'number',
  id: 'string',
  idQuote: 'string',
  idQuoteTabs: 'string',
  idRecurringRevenue: 'string',
  invoiceGroupingId: 'integer',
  isBundleComponent: 'boolean',
  isBundleHeader: 'boolean',
  isDeferrable: 'boolean',
  isHiddenItem: 'boolean',
  isMetadataItem: 'boolean',
  isModTagModified: 'boolean',
  isOptional: 'boolean',
  isOverrideQty: 'boolean',
  isPhaseItem: 'boolean',
  isPrinted: 'boolean',
  isPromotion: 'boolean',
  isProtectedItem: 'boolean',
  isProtectedPrice: 'boolean',
  isRampable: 'boolean',
  isRebate: 'boolean',
  isRecurringTaxable: 'boolean',
  isSelected: 'boolean',
  isShowPrice: 'boolean',
  isSold: 'boolean',
  isTaxable: 'boolean',
  isTotalsIncluded: 'boolean',
  itemCube: 'number',
  itemHeight: 'number',
  itemLength: 'number',
  itemNotes: 'string',
  itemNotesHtml: 'string',
  itemNumber: 'string',
  itemWidth: 'number',
  keywords: 'string',
  lineType: 'string',
  localPriceFormula: 'string',
  longDescription: 'string',
  manufacturerPartNumber: 'string',
  marketingInformation: 'string',
  markup: 'number',
  modifyDate: 'string',
  netCost: 'number',
  onHand: 'integer',
  onHandWarehouse1: 'integer',
  onHandWarehouse2: 'integer',
  onOrder: 'integer',
  optionGroup: 'string',
  optionLocked: 'boolean',
  overridePackageDetails: 'boolean',
  overridePrice: 'number',
  overridePriceModifier: 'string',
  owner: 'string',
  packagePrice: 'number',
  packageQty: 'number',
  parentQuoteItem: 'string',
  pdfAttachment: 'string',
  period: 'string',
  poNumber: 'string',
  posDescription: 'string',
  poStatus: 'string',
  priceConverted: 'number',
  priceModifier: 'string',
  productCategory: 'string',
  productClass: 'string',
  productSubCategory: 'string',
  productType: 'string',
  promotionComment: 'string',
  promotionExpirationDate: 'string',
  pst: 'number',
  pstConverted: 'number',
  pstRate: 'number',
  quantity: 'number',
  quosalDescription: 'string',
  quosalPurchasingNotes: 'string',
  quoteItemPrice: 'number',
  quoteName: 'string',
  quoteReadableId: 'string',
  rampPeriods: 'integer',
  rebateComment: 'string',
  rebateExpirationDate: 'string',
  recurringAmount: 'number',
  recurringBasePrice: 'number',
  recurringCalculatedPriceModifier: 'string',
  recurringCost: 'number',
  recurringCostModifier: 'string',
  recurringExtendedCost: 'number',
  recurringExtendedSuggestedPrice: 'number',
  recurringGst: 'number',
  recurringPrice: 'number',
  recurringPriceModifier: 'string',
  recurringPst: 'number',
  recurringSuggestedPrice: 'number',
  recurringTax: 'number',
  recurringTotal: 'number',
  replacementSku: 'string',
  shortDescription: 'string',
  sortOrder: 'integer',
  source: 'string',
  sourceManufacturerId: 'string',
  sourceManufacturerName: 'string',
  sourceSelectionDetails: 'string',
  sourceVendorId: 'string',
  sourceVendorName: 'string',
  startingCost: 'number',
  stateGovPrice: 'number',
  suggestedPrice: 'number',
  svcSpread: 'number',
  tax: 'number',
  taxCode: 'string',
  taxConverted: 'number',
  taxRate: 'number',
  thumbnail: 'string',
  totalWeight: 'number',
  uom: 'string',
  uomFactor: 'integer',
  uomWeight: 'number',
  uop: 'string',
  uopFactor: 'integer',
  upcNumber: 'string',
  userId: 'string',
  vendorPartNumber: 'string',
  warehouse: 'string',
  warehouseCode: 'string',
  zCustomBool1: 'boolean',
  zCustomBool10: 'boolean',
  zCustomBool2: 'boolean',
  zCustomBool3: 'boolean',
  zCustomBool4: 'boolean',
  zCustomBool5: 'boolean',
  zCustomBool6: 'boolean',
  zCustomBool7: 'boolean',
  zCustomBool8: 'boolean',
  zCustomBool9: 'boolean',
  zCustomDate1: 'string',
  zCustomDate2: 'string',
  zCustomDecimal1: 'number',
  zCustomDecimal10: 'number',
  zCustomDecimal2: 'number',
  zCustomDecimal3: 'number',
  zCustomDecimal4: 'number',
  zCustomDecimal5: 'number',
  zCustomDecimal6: 'number',
  zCustomDecimal7: 'number',
  zCustomDecimal8: 'number',
  zCustomDecimal9: 'number',
  zCustomNotes1: 'string',
  zCustomNotes10: 'string',
  zCustomNotes2: 'string',
  zCustomNotes3: 'string',
  zCustomNotes4: 'string',
  zCustomNotes5: 'string',
  zCustomNotes6: 'string',
  zCustomNotes7: 'string',
  zCustomNotes8: 'string',
  zCustomNotes9: 'string',
  zCustomString1: 'string',
  zCustomString10: 'string',
  zCustomString11: 'string',
  zCustomString12: 'string',
  zCustomString13: 'string',
  zCustomString14: 'string',
  zCustomString15: 'string',
  zCustomString16: 'string',
  zCustomString17: 'string',
  zCustomString18: 'string',
  zCustomString19: 'string',
  zCustomString2: 'string',
  zCustomString20: 'string',
  zCustomString21: 'string',
  zCustomString22: 'string',
  zCustomString23: 'string',
  zCustomString24: 'string',
  zCustomString25: 'string',
  zCustomString3: 'string',
  zCustomString4: 'string',
  zCustomString5: 'string',
  zCustomString6: 'string',
  zCustomString7: 'string',
  zCustomString8: 'string',
  zCustomString9: 'string',
  zCustomText1: 'string',
};

export const quoteItemsOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: { show: { resource: ['quoteItems'] } },
    options: [
      { name: 'Create', value: 'create', description: 'Create quote item', action: 'Create a quote item' },
      { name: 'Delete', value: 'delete', description: 'Delete quote item', action: 'Delete a quote item' },
      { name: 'Get', value: 'get', description: 'Get quote item by ID', action: 'Get a quote item' },
      { name: 'Get Many', value: 'getAll', description: 'List quote items', action: 'Get many quote items' },
      { name: 'Update', value: 'update', description: 'Update quote item (PATCH)', action: 'Update a quote item' },
    ],
    default: 'getAll',
  },
];

export const quoteItemsFields: INodeProperties[] = [
  {
    displayName: 'Item ID',
    name: 'id',
    type: 'string',
    required: true,
    default: '',
    description: 'Quote item ID',
    displayOptions: { show: { resource: ['quoteItems'], operation: ['delete', 'update', 'get'] } },
  },
  {
    displayName: 'Item (JSON)',
    name: 'bodyJson',
    type: 'string',
    typeOptions: { rows: 6 },
    default: '',
    required: true,
    description: 'Raw JSON for QuoteItemView (POST body)',
    displayOptions: { show: { resource: ['quoteItems'], operation: ['create'] } },
  },
  {
    displayName: 'Fields to Update',
    name: 'updateFields',
    type: 'fixedCollection',
    typeOptions: { multipleValues: true },
    placeholder: 'Add Field',
    default: {},
    required: true,
    description: 'Fields to update on the quote item. For boolean fields use "true" or "false". For date fields use ISO format (YYYY-MM-DD).',
    displayOptions: { show: { resource: ['quoteItems'], operation: ['update'] } },
    options: [
      {
        name: 'values',
        displayName: 'Field',
        values: [
          {
            displayName: 'Field',
            name: 'field',
            type: 'options',
            options: [
              { name: 'Approval Content Hash', value: 'approvalContentHash' },
              { name: 'Approval Margin Minimum', value: 'approvalMarginMinimum' },
              { name: 'Approval On Change', value: 'approvalOnChange' },
              { name: 'Approval Price Minimum', value: 'approvalPriceMinimum' },
              { name: 'Base Price', value: 'basePrice' },
              { name: 'Config ID', value: 'configId' },
              { name: 'Config Position', value: 'configPosition' },
              { name: 'Cost', value: 'cost' },
              { name: 'Cost Modifier', value: 'costModifier' },
              { name: 'Crm Reference', value: 'crmReference' },
              { name: 'Cw Agreement', value: 'cwAgreement' },
              { name: 'Cw Class', value: 'cwClass' },
              { name: 'Deferment Periods', value: 'defermentPeriods' },
              { name: 'Dimension1', value: 'dimension1' },
              { name: 'Dimension2', value: 'dimension2' },
              { name: 'Dimension3', value: 'dimension3' },
              { name: 'Dimension4', value: 'dimension4' },
              { name: 'Dimension5', value: 'dimension5' },
              { name: 'Disable Remaps', value: 'disableRemaps' },
              { name: 'Discount', value: 'discount' },
              { name: 'Discount Amount', value: 'discountAmount' },
              { name: 'Discount Amount Converted', value: 'discountAmountConverted' },
              { name: 'Enforce Item Mod Tags', value: 'enforceItemModTags' },
              { name: 'Etilize Product ID', value: 'etilizeProductId' },
              { name: 'Etilize Serialized Attributes', value: 'etilizeSerializedAttributes' },
              { name: 'Extended Cost', value: 'extendedCost' },
              { name: 'Extended Price', value: 'extendedPrice' },
              { name: 'Extended Price Converted', value: 'extendedPriceConverted' },
              { name: 'Extended Suggested Price', value: 'extendedSuggestedPrice' },
              { name: 'External Quote Number', value: 'externalQuoteNumber' },
              { name: 'External Reference', value: 'externalReference' },
              { name: 'Factor Item Mfp', value: 'factorItemMfp' },
              { name: 'Factor Qty Fixed', value: 'factorQtyFixed' },
              { name: 'Factor Qty Multiplier', value: 'factorQtyMultiplier' },
              { name: 'Federal Gov Price', value: 'federalGovPrice' },
              { name: 'Gross Margin', value: 'grossMargin' },
              { name: 'Grouping Code', value: 'groupingCode' },
              { name: 'Gsa Price', value: 'gsaPrice' },
              { name: 'Gst', value: 'gst' },
              { name: 'Gst Converted', value: 'gstConverted' },
              { name: 'Gst Rate', value: 'gstRate' },
              { name: 'ID', value: 'id' },
              { name: 'ID Quote', value: 'idQuote' },
              { name: 'ID Quote Tabs', value: 'idQuoteTabs' },
              { name: 'ID Recurring Revenue', value: 'idRecurringRevenue' },
              { name: 'Invoice Grouping ID', value: 'invoiceGroupingId' },
              { name: 'Is Bundle Component', value: 'isBundleComponent' },
              { name: 'Is Bundle Header', value: 'isBundleHeader' },
              { name: 'Is Deferrable', value: 'isDeferrable' },
              { name: 'Is Hidden Item', value: 'isHiddenItem' },
              { name: 'Is Metadata Item', value: 'isMetadataItem' },
              { name: 'Is Mod Tag Modified', value: 'isModTagModified' },
              { name: 'Is Optional', value: 'isOptional' },
              { name: 'Is Override Qty', value: 'isOverrideQty' },
              { name: 'Is Phase Item', value: 'isPhaseItem' },
              { name: 'Is Printed', value: 'isPrinted' },
              { name: 'Is Promotion', value: 'isPromotion' },
              { name: 'Is Protected Item', value: 'isProtectedItem' },
              { name: 'Is Protected Price', value: 'isProtectedPrice' },
              { name: 'Is Rampable', value: 'isRampable' },
              { name: 'Is Rebate', value: 'isRebate' },
              { name: 'Is Recurring Taxable', value: 'isRecurringTaxable' },
              { name: 'Is Selected', value: 'isSelected' },
              { name: 'Is Show Price', value: 'isShowPrice' },
              { name: 'Is Sold', value: 'isSold' },
              { name: 'Is Taxable', value: 'isTaxable' },
              { name: 'Is Totals Included', value: 'isTotalsIncluded' },
              { name: 'Item Cube', value: 'itemCube' },
              { name: 'Item Height', value: 'itemHeight' },
              { name: 'Item Length', value: 'itemLength' },
              { name: 'Item Notes', value: 'itemNotes' },
              { name: 'Item Notes Html', value: 'itemNotesHtml' },
              { name: 'Item Number', value: 'itemNumber' },
              { name: 'Item Width', value: 'itemWidth' },
              { name: 'Keywords', value: 'keywords' },
              { name: 'Line Type', value: 'lineType' },
              { name: 'Local Price Formula', value: 'localPriceFormula' },
              { name: 'Long Description', value: 'longDescription' },
              { name: 'Manufacturer Part Number', value: 'manufacturerPartNumber' },
              { name: 'Marketing Information', value: 'marketingInformation' },
              { name: 'Markup', value: 'markup' },
              { name: 'Modify Date', value: 'modifyDate' },
              { name: 'Net Cost', value: 'netCost' },
              { name: 'On Hand', value: 'onHand' },
              { name: 'On Hand Warehouse1', value: 'onHandWarehouse1' },
              { name: 'On Hand Warehouse2', value: 'onHandWarehouse2' },
              { name: 'On Order', value: 'onOrder' },
              { name: 'Option Group', value: 'optionGroup' },
              { name: 'Option Locked', value: 'optionLocked' },
              { name: 'Override Package Details', value: 'overridePackageDetails' },
              { name: 'Override Price', value: 'overridePrice' },
              { name: 'Override Price Modifier', value: 'overridePriceModifier' },
              { name: 'Owner', value: 'owner' },
              { name: 'Package Price', value: 'packagePrice' },
              { name: 'Package Qty', value: 'packageQty' },
              { name: 'Parent Quote Item', value: 'parentQuoteItem' },
              { name: 'Pdf Attachment', value: 'pdfAttachment' },
              { name: 'Period', value: 'period' },
              { name: 'Po Number', value: 'poNumber' },
              { name: 'Po Status', value: 'poStatus' },
              { name: 'Pos Description', value: 'posDescription' },
              { name: 'Price Converted', value: 'priceConverted' },
              { name: 'Price Modifier', value: 'priceModifier' },
              { name: 'Product Category', value: 'productCategory' },
              { name: 'Product Class', value: 'productClass' },
              { name: 'Product Sub Category', value: 'productSubCategory' },
              { name: 'Product Type', value: 'productType' },
              { name: 'Promotion Comment', value: 'promotionComment' },
              { name: 'Promotion Expiration Date', value: 'promotionExpirationDate' },
              { name: 'Pst', value: 'pst' },
              { name: 'Pst Converted', value: 'pstConverted' },
              { name: 'Pst Rate', value: 'pstRate' },
              { name: 'Quantity', value: 'quantity' },
              { name: 'Quosal Description', value: 'quosalDescription' },
              { name: 'Quosal Purchasing Notes', value: 'quosalPurchasingNotes' },
              { name: 'Quote Item Price', value: 'quoteItemPrice' },
              { name: 'Quote Name', value: 'quoteName' },
              { name: 'Quote Readable ID', value: 'quoteReadableId' },
              { name: 'Ramp Periods', value: 'rampPeriods' },
              { name: 'Rebate Comment', value: 'rebateComment' },
              { name: 'Rebate Expiration Date', value: 'rebateExpirationDate' },
              { name: 'Recurring Amount', value: 'recurringAmount' },
              { name: 'Recurring Base Price', value: 'recurringBasePrice' },
              { name: 'Recurring Calculated Price Modifier', value: 'recurringCalculatedPriceModifier' },
              { name: 'Recurring Cost', value: 'recurringCost' },
              { name: 'Recurring Cost Modifier', value: 'recurringCostModifier' },
              { name: 'Recurring Extended Cost', value: 'recurringExtendedCost' },
              { name: 'Recurring Extended Suggested Price', value: 'recurringExtendedSuggestedPrice' },
              { name: 'Recurring Gst', value: 'recurringGst' },
              { name: 'Recurring Price', value: 'recurringPrice' },
              { name: 'Recurring Price Modifier', value: 'recurringPriceModifier' },
              { name: 'Recurring Pst', value: 'recurringPst' },
              { name: 'Recurring Suggested Price', value: 'recurringSuggestedPrice' },
              { name: 'Recurring Tax', value: 'recurringTax' },
              { name: 'Recurring Total', value: 'recurringTotal' },
              { name: 'Replacement Sku', value: 'replacementSku' },
              { name: 'Short Description', value: 'shortDescription' },
              { name: 'Sort Order', value: 'sortOrder' },
              { name: 'Source', value: 'source' },
              { name: 'Source Manufacturer ID', value: 'sourceManufacturerId' },
              { name: 'Source Manufacturer Name', value: 'sourceManufacturerName' },
              { name: 'Source Selection Details', value: 'sourceSelectionDetails' },
              { name: 'Source Vendor ID', value: 'sourceVendorId' },
              { name: 'Source Vendor Name', value: 'sourceVendorName' },
              { name: 'Starting Cost', value: 'startingCost' },
              { name: 'State Gov Price', value: 'stateGovPrice' },
              { name: 'Suggested Price', value: 'suggestedPrice' },
              { name: 'Svc Spread', value: 'svcSpread' },
              { name: 'Tax', value: 'tax' },
              { name: 'Tax Code', value: 'taxCode' },
              { name: 'Tax Converted', value: 'taxConverted' },
              { name: 'Tax Rate', value: 'taxRate' },
              { name: 'Thumbnail', value: 'thumbnail' },
              { name: 'Total Weight', value: 'totalWeight' },
              { name: 'Uom', value: 'uom' },
              { name: 'Uom Factor', value: 'uomFactor' },
              { name: 'Uom Weight', value: 'uomWeight' },
              { name: 'Uop', value: 'uop' },
              { name: 'Uop Factor', value: 'uopFactor' },
              { name: 'Upc Number', value: 'upcNumber' },
              { name: 'User ID', value: 'userId' },
              { name: 'Vendor Part Number', value: 'vendorPartNumber' },
              { name: 'Warehouse', value: 'warehouse' },
              { name: 'Warehouse Code', value: 'warehouseCode' },
              { name: 'Z Custom Bool1', value: 'zCustomBool1' },
              { name: 'Z Custom Bool10', value: 'zCustomBool10' },
              { name: 'Z Custom Bool2', value: 'zCustomBool2' },
              { name: 'Z Custom Bool3', value: 'zCustomBool3' },
              { name: 'Z Custom Bool4', value: 'zCustomBool4' },
              { name: 'Z Custom Bool5', value: 'zCustomBool5' },
              { name: 'Z Custom Bool6', value: 'zCustomBool6' },
              { name: 'Z Custom Bool7', value: 'zCustomBool7' },
              { name: 'Z Custom Bool8', value: 'zCustomBool8' },
              { name: 'Z Custom Bool9', value: 'zCustomBool9' },
              { name: 'Z Custom Date1', value: 'zCustomDate1' },
              { name: 'Z Custom Date2', value: 'zCustomDate2' },
              { name: 'Z Custom Decimal1', value: 'zCustomDecimal1' },
              { name: 'Z Custom Decimal10', value: 'zCustomDecimal10' },
              { name: 'Z Custom Decimal2', value: 'zCustomDecimal2' },
              { name: 'Z Custom Decimal3', value: 'zCustomDecimal3' },
              { name: 'Z Custom Decimal4', value: 'zCustomDecimal4' },
              { name: 'Z Custom Decimal5', value: 'zCustomDecimal5' },
              { name: 'Z Custom Decimal6', value: 'zCustomDecimal6' },
              { name: 'Z Custom Decimal7', value: 'zCustomDecimal7' },
              { name: 'Z Custom Decimal8', value: 'zCustomDecimal8' },
              { name: 'Z Custom Decimal9', value: 'zCustomDecimal9' },
              { name: 'Z Custom Notes1', value: 'zCustomNotes1' },
              { name: 'Z Custom Notes10', value: 'zCustomNotes10' },
              { name: 'Z Custom Notes2', value: 'zCustomNotes2' },
              { name: 'Z Custom Notes3', value: 'zCustomNotes3' },
              { name: 'Z Custom Notes4', value: 'zCustomNotes4' },
              { name: 'Z Custom Notes5', value: 'zCustomNotes5' },
              { name: 'Z Custom Notes6', value: 'zCustomNotes6' },
              { name: 'Z Custom Notes7', value: 'zCustomNotes7' },
              { name: 'Z Custom Notes8', value: 'zCustomNotes8' },
              { name: 'Z Custom Notes9', value: 'zCustomNotes9' },
              { name: 'Z Custom String1', value: 'zCustomString1' },
              { name: 'Z Custom String10', value: 'zCustomString10' },
              { name: 'Z Custom String11', value: 'zCustomString11' },
              { name: 'Z Custom String12', value: 'zCustomString12' },
              { name: 'Z Custom String13', value: 'zCustomString13' },
              { name: 'Z Custom String14', value: 'zCustomString14' },
              { name: 'Z Custom String15', value: 'zCustomString15' },
              { name: 'Z Custom String16', value: 'zCustomString16' },
              { name: 'Z Custom String17', value: 'zCustomString17' },
              { name: 'Z Custom String18', value: 'zCustomString18' },
              { name: 'Z Custom String19', value: 'zCustomString19' },
              { name: 'Z Custom String2', value: 'zCustomString2' },
              { name: 'Z Custom String20', value: 'zCustomString20' },
              { name: 'Z Custom String21', value: 'zCustomString21' },
              { name: 'Z Custom String22', value: 'zCustomString22' },
              { name: 'Z Custom String23', value: 'zCustomString23' },
              { name: 'Z Custom String24', value: 'zCustomString24' },
              { name: 'Z Custom String25', value: 'zCustomString25' },
              { name: 'Z Custom String3', value: 'zCustomString3' },
              { name: 'Z Custom String4', value: 'zCustomString4' },
              { name: 'Z Custom String5', value: 'zCustomString5' },
              { name: 'Z Custom String6', value: 'zCustomString6' },
              { name: 'Z Custom String7', value: 'zCustomString7' },
              { name: 'Z Custom String8', value: 'zCustomString8' },
              { name: 'Z Custom String9', value: 'zCustomString9' },
              { name: 'Z Custom Text1', value: 'zCustomText1' },
            ],
            default: 'shortDescription',
            description: 'The quote item field to update',
          },
          {
            displayName: 'Value',
            name: 'value',
            type: 'string',
            default: '',
            description: 'The new value for the field',
          },
        ],
      },
    ],
  },
];

export async function executeQuoteItems(
  this: IExecuteFunctions,
  i: number,
  returnData: INodeExecutionData[],
): Promise<void> {
  const operation = this.getNodeParameter('operation', i) as string;

  if (operation === 'getAll') {
    const returnAll = this.getNodeParameter('returnAll', i, false) as boolean;
    const pageSize = this.getNodeParameter('pageSize', i, 50) as number;
    const limit = this.getNodeParameter('limit', i, 100) as number;
    const filters = this.getNodeParameter('filters', i, {}) as {
      conditions?: Array<{ field?: string; operator?: string; valueType?: string; value?: string }>;
    };
    const filterLogic = this.getNodeParameter('filterLogic', i, 'and') as 'and' | 'or';
    const additionalOptions = this.getNodeParameter('additionalOptions', i, {}) as { rawConditions?: string };
    const conditions = buildFiltersFromUi(filters, filterLogic, additionalOptions.rawConditions);
    const includeFieldsRaw = this.getNodeParameter('includeFields', i, '') as string | string[];
    const includeFields = Array.isArray(includeFieldsRaw) ? includeFieldsRaw.join(',') : includeFieldsRaw;
    const showAllVersions = this.getNodeParameter('showAllVersions', i, false) as boolean;

    const qs: IDataObject = {};
    if (conditions) qs.conditions = conditions;
    if (includeFields) qs.includeFields = includeFields;
    if (showAllVersions) qs.showAllVersions = showAllVersions;

    if (returnAll) {
      const all = (await cpqApiRequestAllItems.call(
        this,
        '',
        'GET',
        '/api/quoteItems',
        {},
        qs as IDataObject,
        {},
        undefined,
        MAX_PAGE_SIZE,
      )) as unknown[];
      for (const entry of all as IDataObject[]) returnData.push({ json: entry });
    } else {
      const effectivePageSize = Math.min(typeof limit === 'number' ? limit : pageSize, MAX_PAGE_SIZE);
      const some = (await cpqApiRequestAllItems.call(
        this,
        '',
        'GET',
        '/api/quoteItems',
        {},
        qs as IDataObject,
        {},
        limit,
        effectivePageSize,
      )) as unknown[];
      for (const entry of some as IDataObject[]) returnData.push({ json: entry });
    }
  }

  if (operation === 'create') {
    const bodyJson = this.getNodeParameter('bodyJson', i) as string;
    let body: IDataObject | IDataObject[] = {};
    if (bodyJson) {
      body = JSON.parse(bodyJson) as IDataObject;
    }
    const res = (await cpqApiRequest.call(this, 'POST', `/api/quoteItems`, body)) as IDataObject;
    returnData.push({ json: res as IDataObject });
  }

  if (operation === 'delete') {
    const id = this.getNodeParameter('id', i) as string;
    await cpqApiRequest.call(this, 'DELETE', `/api/quoteItems/${encodeURIComponent(id)}`);
    returnData.push({ json: { id, success: true } });
  }

  if (operation === 'update') {
    const id = this.getNodeParameter('id', i) as string;
    const updateFields = this.getNodeParameter('updateFields', i, {}) as {
      values?: Array<{ field: string; value: string }>;
    };
    const rows = updateFields.values ?? [];
    if (rows.length === 0) {
      throw new NodeOperationError(this.getNode(), 'Add at least one field to update.', { itemIndex: i });
    }
    const ops = rows.map(({ field, value }) => ({
      op: 'replace' as const,
      path: `/${field}`,
      value: castUpdateValue(this.getNode(), i, value, QUOTE_ITEM_FIELD_TYPES[field] ?? 'string'),
    }));
    const patchBody = prepareJsonPatch(ops);
    const res = (await cpqApiRequest.call(
      this,
      'PATCH',
      `/api/quoteItems/${encodeURIComponent(id)}`,
      patchBody,
    )) as IDataObject;
    returnData.push({ json: res });
  }

  if (operation === 'get') {
    const id = this.getNodeParameter('id', i) as string;
    const res = (await cpqApiRequest.call(this, 'GET', `/api/quoteItems/${encodeURIComponent(id)}`)) as IDataObject;
    returnData.push({ json: res as IDataObject });
  }
}


